- name: Get service facts
  service_facts:

- name: Get variables
  include_vars: vars/prometheus-exporter-vars.yml
      
- block:    
  - name: Install git/go
    package:
      name:
        - go
        - git
      state: latest

  - name: Add exporter systemd file
    copy:
      src: "assets/systemd/{{ exporter_name }}.service"
      dest: "/usr/lib/systemd/system/{{ exporter_name }}.service"
      owner: root
      group: root
      mode: 0644

  - name: Build Prometheus exporter
    shell: |
      eval $(go env)
      go get github.com/aerospike/{{ exporter_name }}
      cd $GOPATH/src/github.com/aerospike/{{ exporter_name }}
      go build -o {{ exporter_name }} .
      mkdir -p /etc/{{ exporter_name }}
      curl https://raw.githubusercontent.com/aerospike/{{ exporter_name }}/master/ape.toml -o {{ exporter_config_path }}
      sed -i 's/^db_host.*$/db_host="localhost"/' {{ exporter_config_path }}
      sed -i 's|^log_file\s*=.*$|log_file="/var/log/aerospike/{{ exporter_name }}.log"|' {{ exporter_config_path }}
      sed -i 's|^log_level\s*=.*$|log_level="info"|' {{ exporter_config_path }}
      sed -i "s/^tags.*$/tags=['{{ cluster_id }}']/" {{ exporter_config_path }}
      if [ "{{ tls_enabled }}" == "True" ]
      then
      # Use the pipe separator for sed to avoid difficulties with / characters in paths
        sed -i 's|^root_ca=.*$|root_ca="{{ certificates_directory }}/ca.crt"|' {{ exporter_config_path }}
        sed -i 's|^cert_file=.*$|cert_file="{{ certificates_directory }}/server.crt"|' {{ exporter_config_path }}
        sed -i 's|^key_file=.*$|key_file="{{ private_key_directory }}/server.key"|' {{ exporter_config_path }}
        sed -i 's|^db_port=.*$|db_port={{ tls_service_port }}|' {{ exporter_config_path }}
        sed -i 's|^node_tls_name=.*$|node_tls_name="{{ tls_name }}"|' {{ exporter_config_path }}
      fi
      rm /usr/local/bin/{{exporter_name}}
      ln -s $(pwd)/{{ exporter_name }} /usr/local/bin/{{ exporter_name }}
      systemctl daemon-reload
  when: hostvars[inventory_hostname].services[exporter_service_name] is not defined

- name: "Start {{ exporter_name }}, if not started"
  service:
    name: "{{ exporter_name}}"
    state: restarted
