- name: "Copy Aerospike configuration to servers and restart"
  hosts: "{{ cluster_tag }}"
  gather_facts: true
  become: yes
  remote_user: "{{ os_config['remote_user'] }}"
  vars_files:
  - vars/cluster-config.yml
  - vars/constants.yml
  - vars/os-level-config.yml  
  tasks:
  - name: Import configuration properties
    include_vars: 
      dir: vars
    
  - name: aerospike.conf
    import_tasks: modules/aerospike-configuration-tasks.yml

  - name: Restart Aerospike service
    shell: 
      cmd: "service aerospike restart"
