# AWS - Region and AZ settings
# ========================
aws_region: us-east-1

# We specify cluster in terms of nodes per az
cluster_az_list:
  - 'a'
  - 'b'
  - 'd'

# We specify client count in terms of nodes per az
# Default to choosing the first in the cluster_az list
client_az_list:
  - "{{ cluster_az_list[0] }}"

# AWS - IP details for generated sub-nets
# ===================
vpc_cidr: 10.0.0.0/16
subnet_cidr: 10.0.0.0/22 # IP range permitted for intra-cluster transport

# Security
# ========
# By default public ports (Grafana(4000),Prometheus(9090),Spark Web ports (8080,8081))
# will be locked to your public ip. If you want to use a different address range uncomment the line below
# public_port_access_cidr: "10.0.0.1/32"

# User used to access your instances using the quick access ssh scripts. Change if not using AWS
remote_user: "{{ os_config['remote_user']}}"

