# AWS - Region and AZ settings
# ========================
aws_region: us-east-1

# We specify cluster in terms of nodes per az
cluster_az_list:
  - 'a'
  - 'b'
  - 'd'

# We specify client count in terms of nodes per az
# Default to choosing the first in the cluster_az list
client_az_list:
  - "{{ cluster_az_list[0] }}"

# AWS - IP details for generated sub-nets
# ===================
vpc_cidr: 10.0.0.0/16
subnet_cidr: 10.0.0.0/22 # IP range permitted for intra-cluster transport
