# Instance types, hosts per zone, partitions per device
# You may wish to change these
# =================================
cluster_instance_type: c5d.large
cluster_hosts_per_az : 1
partitions_per_device: 4

# Aerospike client type and count
client_instance_type: "{{ cluster_instance_type }}"
aerospike_client_per_az_count: 1

# Aerospike monitorign type
monitoring_instance_type: "{{ cluster_instance_type }}"

# Spark worker count
spark_instance_type: "{{ cluster_instance_type }}"
spark_worker_per_az_count: 1

# Installation configuration
# ===================================

# Whether to use enterprise
# Set to false by default so will run without features.conf
enterprise: false

# Whether to enable encryption at rest
encryption_at_rest: false

# Whether to use TLS
tls_enabled: false

# Strong consistency
strong_consistency: false

# All Flash
all_flash: false

# Monitoring
monitoring_enabled: true

# Distribution
aerospike_distribution: "el7" 
# Note that el6 id not supported for Aerospike 5.5 and higher
# If you want to use a debian or ubuntu or install, you will need to change the ami_locator_string below

# Version number
aerospike_version: "latest" 
# Use full version number e.g. 4.8.0.8 'latest' is also recognized. 

# AMI - will use the most recent Amazon AMI matching the name below
ami_locator_string: "amzn2-ami-hvm-2.0.*-x86_64-gp2*"

# Replication factor
replication_factor: 2

# Proportion of total memory to assign to Aerospike - used in configuration template - see assets folder
aerospike_mem_pct: 80

# Default Rack ID
rack_id : 101

# Cluster ID - used by Prometheus exporter
cluster_id: "CL-01"



